apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: myproject
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
